apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-processor
  namespace: default
  labels:
    app: log-processor
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: log-processor
  template:
    metadata:
      labels:
        app: log-processor
        version: v1
    spec:
      containers:
      - name: log-processor
        image: log-processor:latest
        imagePullPolicy: Never
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: redis-host
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis-password
        - name: REDIS_CHANNEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: redis-channel
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
